### ISSUE TITLE
Theorem 4.14  - stable marriages worst case

### ISSUE THREAD

**Issue by mikegedelman** [pim-book/exercises#12]
> Since there are exactly _n_ preferences in the list and exactly _n_ Suitors, we get the bound a<sub>t</sub> <= n<sup>2</sup> (each Suitor could be at the very end of their list; come up with an example to show this can happen!)

I spent way too long trying to write out such an example and gave up, and went searching for examples. According to a few search results, the worst case appears to actually be n<sup>2</sup> - 2n + 2, which I won't attempt to prove, since I'm not very practiced at maths, which is why I'm reading this book.

[source](https://math.stackexchange.com/questions/1410898/worst-case-for-the-stable-marriage-problem)

**Comment by j2kun** [comment]
I believe the existing sources are counting the number of proposals, which is not the same as what we're counting here (the number of rejections, but you're right, the n^2 upper bound is not tight when you're counting rejections. The example I had in mind, which I incorrectly called "all suitors are at the ends of their lists" is one for which all suitors are at the second to last entry in their list, except for one suitor who is at the last entry.

In this scenario, all N of the Suitors are competing for N-1 Suiteds, and it's configured in such a way that in each round one Suitor is rejected, and then proposes to their next-most-preferred Suited, and the Suited they propose to prefers them by exactly one unit more than who the Suited was previously holding on to.

Here is an example of this for n=4:

```python
    suitor0 = Suitor(0, [0, 1, 2, 3])
    suitor1 = Suitor(1, [1, 2, 0, 3])
    suitor2 = Suitor(2, [2, 0, 1, 3])
    suitor3 = Suitor(3, [0, 1, 2, 3])

    suited0 = Suited(0, [1, 2, 3, 0])
    suited1 = Suited(1, [2, 3, 0, 1])
    suited2 = Suited(2, [3, 0, 1, 2])
    suited3 = Suited(3, [0, 1, 2, 3])
```

In this setup, there are (n-1)^2 = 9 total rejections, one in each round, and at the end the first three Suiteds all get their top pick, while the last Suited is never proposed to until the final round so it's arbitrary. And there are n*(n-1) + 1 = n^2 - n + 1 total proposals. 

I think you can generalize this to any n by extending the pattern of symmetry in the n=4 example above. In more detail, all Suitor preferences have N in the last index, and the top-left (n-1)x(n-1) submatrix have each row being a shift of the one before it (the N Suitors are competing over the N-1 Suiteds). The Suiteds, have rows that shift in the same way as the Suitors, but starting so that each Suited is first proposed to by their last choice.

Here is a git diff that incorporates the above example so you can test it out on the code sample.

```
diff --git a/stable-marriages/stable_marriage.py b/stable-marriages/stable_marriage.py
index fdfd229..2becf21 100644
--- a/stable-marriages/stable_marriage.py
+++ b/stable-marriages/stable_marriage.py
@@ -77,20 +77,28 @@ def stable_marriage(suitors, suiteds):
     Returns:
         A dict {Suitor: Suited} matching Suitors to Suiteds.
     """
+    rejection_count = 0
     unassigned = set(suitors)
+    round_num = 1
 
     while len(unassigned) > 0:
+        print(f"Round {round_num}")
         for suitor in unassigned:
             next_to_propose_to = suiteds[suitor.preference()]
             next_to_propose_to.add_suitor(suitor)
+            print(f"{suitor} -> {next_to_propose_to}")
         unassigned = set()
 
         for suited in suiteds:
             unassigned |= suited.reject()
 
         for suitor in unassigned:
+            rejection_count += 1
             suitor.post_rejection()  # have some ice cream
 
+        round_num += 1
+
+    print(rejection_count)
     return dict([(suited.held, suited) for suited in suiteds])
 
 
@@ -125,3 +133,19 @@ def verify_stable(suitors, suiteds, marriage):
             return False, (suitor, suited)
 
     return True
+
+
+if __name__ == "__main__":
+    suitor0 = Suitor(0, [0, 1, 2, 3])
+    suitor1 = Suitor(1, [1, 2, 0, 3])
+    suitor2 = Suitor(2, [2, 0, 1, 3])
+    suitor3 = Suitor(3, [0, 1, 2, 3])
+
+    suited0 = Suited(0, [1, 2, 3, 0])
+    suited1 = Suited(1, [2, 3, 0, 1])
+    suited2 = Suited(2, [3, 0, 1, 2])
+    suited3 = Suited(3, [0, 1, 2, 3])
+
+    stable_marriage(
+        [suitor0, suitor1, suitor2, suitor3],
+        [suited0, suited1, suited2, suited3])
```

**Comment by j2kun** [comment]
Ah, and I think the "+2" part of what you saw is because they add one more "round" for the round in which there are no new proposals. So that should be the same as the example I gave above.

Sorry you went through all that trouble to find an example :( I hope you at least understand the worst case of this algorithm a bit better now :)

**Comment by mikegedelman** [comment]
> The example I had in mind, which I incorrectly called "all suitors are at the ends of their lists" is one for which all suitors are at the second to last entry in their list, except for one suitor who is at the last entry.

This is the crux of what I was running up against.

No worries though, it was fun. Thanks for the detailed response!
