### ISSUE TITLE
Exercise 2.2.3 - Factoring polynomials

### ISSUE THREAD

**Issue by DinoPollano** [pim-book/exercises#15]
Hi, so I'm enjoying the book so far and a lot of it is going in at the minute. I'm finding writing examples down and then testing them in code to be an effective way at gaining intuition.
However I'm struggling with correctly creating real-world examples in exercise 2.2.3:
I originally tried a 3rd degree polynomial i.e.  ![CodeCogsEqn](https://user-images.githubusercontent.com/5576321/135711902-7ab899b2-6e49-40f8-8291-45eeb3a200b5.gif)
but thought maybe I should've tried something easier so I went with a 2nd degree. 
My assumption that if ![CodeCogsEqn (1)](https://user-images.githubusercontent.com/5576321/135711963-1425d168-673f-4502-818a-380e490801f9.gif) and ![CodeCogsEqn (2)](https://user-images.githubusercontent.com/5576321/135712008-8c322bab-2ce0-4d20-be6a-80606ee1d084.gif)
 where ![CodeCogsEqn (3)](https://user-images.githubusercontent.com/5576321/135712206-34702e79-19e9-4095-b9ac-171449dbbae2.gif) and ![CodeCogsEqn (4)](https://user-images.githubusercontent.com/5576321/135712234-9a01c6c9-3eb7-4c07-8433-471c6571d71c.gif) , therefore ![CodeCogsEqn (5)](https://user-images.githubusercontent.com/5576321/135712274-16620eb2-983c-4876-bc32-440d7df8471e.gif)

So for a real-world example:
![CodeCogsEqn (6)](https://user-images.githubusercontent.com/5576321/135712323-c5a457e0-3022-4b21-9c0c-d3a073067ef3.gif)
 
![CodeCogsEqn (7)](https://user-images.githubusercontent.com/5576321/135712412-64b01956-f01f-452b-8029-4a9dbe8233cb.gif)
![CodeCogsEqn (8)](https://user-images.githubusercontent.com/5576321/135712453-763b7189-f795-4595-b7e5-489aa2d39471.gif)
![CodeCogsEqn (9)](https://user-images.githubusercontent.com/5576321/135712491-3de28d51-d437-4a8d-884e-7fe11dbd01ae.gif)
If concentrate on the b coefficients then ![CodeCogsEqn (10)](https://user-images.githubusercontent.com/5576321/135712539-9ca83dd6-36c4-4ac5-9ece-4601590b1f12.gif) and ![CodeCogsEqn (11)](https://user-images.githubusercontent.com/5576321/135712552-d7f45236-b9eb-4666-8809-266a1cbc5b3e.gif)
 
![CodeCogsEqn (12)](https://user-images.githubusercontent.com/5576321/135712601-aacefe7a-9ed6-4c7c-8311-92f683f0093e.gif)
I  believe ![CodeCogsEqn (13)](https://user-images.githubusercontent.com/5576321/135712638-f27737d8-4b7c-4bb8-9999-9026a35d2f3d.gif) then just become 8 

This is where my abilities and conception of maths start to disrail:
I try to get ![CodeCogsEqn (14)](https://user-images.githubusercontent.com/5576321/135712737-6a6b2157-9321-40ac-a619-b9ee4c47ce80.gif)

![CodeCogsEqn (16)](https://user-images.githubusercontent.com/5576321/135712746-07c665cb-96eb-4c00-b659-8bab831b1075.gif)
 
![CodeCogsEqn (17)](https://user-images.githubusercontent.com/5576321/135712754-c7b5fe2f-0220-4cc6-9f18-ffe6a2603807.gif)

So then it's ![CodeCogsEqn (18)](https://user-images.githubusercontent.com/5576321/135712764-42d87f00-a4bd-493c-b577-2a2d9e4ddb8f.gif)
Which then starts to hurt the head...
At this point I decide I've gone down the wrong path and I've made a (probably obvious) mistake somewhere, I'd appreciate any feedback or help given, my apologies for the long post.

 I also have another question (which may be related to this?) I don't quite know how you break up ![CodeCogsEqn (19)](https://user-images.githubusercontent.com/5576321/135712893-408611e8-bcc5-4988-9aae-b24fb47f153e.gif) into ![CodeCogsEqn (20)](https://user-images.githubusercontent.com/5576321/135712912-1b1995b1-d69f-4304-8def-1fb2efae62e0.gif) and ![CodeCogsEqn (21)](https://user-images.githubusercontent.com/5576321/135712936-d26baa0b-14df-4cee-ba24-9679f96629eb.gif) but that's not in an exercise so I'm happy for this to go unanswered

**Comment by j2kun** [comment]
For exercise 2.2.3, you do not necessarily need to derive a general algorithm to factor any polynomial, though I applaud you for trying :)

Instead, I just wanted you to be aware of the concept of "factors" in terms of what the definition means. Based on your question here, you clearly understand that well. And in terms of what an example looks like, it's much easier to find an example by coming up with the factors first. E.g., `(x-1)` and `(x^2+1)` are factors of `(x-1)(x^2+1)(x+3) = x^4 + 2x^3 - 2x^2 + 2x - 3`. I just picked some random small factors and multiplied them together. You could also, if you like, leave the coefficients unspecified and use an example like `(x-a)(x^2+b) = x^3 + bx - ax^2 - ab`.

But one thing you've stumbled upon is the age-old wisdom that multiplying is a hard operation to reverse. For numbers this is true (factoring big integers is hard, which is why RSA is a cryptosystem, see exercise 16.10), and for polynomials this is also true. Though for small-degree polynomials like quadratics, there are known formulas that work for any coefficients (you may recall the quadratic formula and "completing the square" from math classes long ago), in general a large-degree polynomial has no easy "formula" for factoring. This is a theorem with a _long_ history of failed proofs, and solving it took many centuries and the invention of new mathematics (see Chapter 16, Exercise 16.13 and Fred Akalin’s essay, [“Why is the Quintic Unsolvable?”](https://www.akalin.com/quintic-unsolvability)).

So don't feel bad! When learning math—even basic subjects!—it's remarkably easy to stumble into extremely hard problems. Indeed, the example you wrote down (`10 - 4x + 8x^2`) does not have any factors with real coefficients, only factors that use complex (imaginary) numbers. Its two factors are `x - (1 + sqrt(-19))/4` and `x - (1 - sqrt(-19))/4`. For quadratic polynomials you can tell when you will have real factors using the following reasoning. First, if a degree-2 polynomial `P(x)` has smaller-degree factors with real numbers, then they have to be degree 1. Degree-1 polynomials have the form `(x-a)` (where `a` is a real number), and so if you plug in `x=a` into `P(x)` you will get zero. This means that the graph of the polynomial has to cross the x-axis exactly at `x=a`. If you plot your chosen polynomial, you can be quickly convinced that it always lies above the x-axis. (Note: this was a little "proof by contrapositive" which you'll see in Chapter 4)

<img width="486" alt="Screen Shot 2021-10-04 at 6 46 41 AM" src="https://user-images.githubusercontent.com/2467754/135862781-c25653c1-21ea-43e8-a5c3-d8b672988a1f.png">

Hope that helps, and let me know if you have any other questions!

**Comment by DinoPollano** [comment]
Oh man 
> it's remarkably easy to stumble into extremely hard problems. 

Is a very accurate statement. Thanks for your response, I should've just started with the factors! I am (or at least was) experienced with complex numbers, but it's been ages since I've factored down complex polynomials and I've definitely not got the intuition yet.  Your fact on being able to tell if a quadratic will have real factors makes a lot of sense.
 I originally tried plotting the polynomial I had in desmos and working out different values of coefficients with the derived version so they would match but after a few different attempts at working them out and then considering making something in Python that would generate random pairs of coefficients until something came out looking correct I realised I was probably going about it the wrong way. 
 
 Anyway thanks for your response! I shall persevere!
